using System.Collections.Generic;
using System.Linq;
using NexusSupport.SourceGenerator.Models;

namespace NexusSupport.SourceGenerator.Rendering;

internal static class ServiceRegistrationSourceBuilder
{
    public static string RenderRegistrationLine(ServiceRegistration registration) =>
        registration.InterfaceType is not null
            ? $"services.Add{registration.LifeTime}<{registration.InterfaceType}, {registration.ImplementationType}>();"
            : $"services.Add{registration.LifeTime}<{registration.ImplementationType}>();";

    public static string RenderExtensionClass(IEnumerable<string> registrationLines, string assemblyName)
    {
        var orderedLines = registrationLines.OrderBy(static line => line, System.StringComparer.Ordinal);

        return $$"""
            // <auto-generated/>
            using Microsoft.Extensions.DependencyInjection;

            namespace Nexus.Generated;

            public static class ServiceRegistrationExtensions_{{assemblyName}}
            {
                public static IServiceCollection AddGeneratedServices(this IServiceCollection services)
                {
                    {{string.Join("\n            ", orderedLines)}}
                    return services;
                }
            }
            """;
    }
}
