namespace NexusSupport.SourceGenerator.Attributes;

internal static class ServiceAttributeSource
{
    public const string HintName = "ServiceAttribute.g.cs";

    public const string SourceText = """
        // <auto-generated/>
        namespace Nexus.Generated
        {
            internal enum ServiceLifetime
            {
                Transient,
                Scoped,
                Singleton,
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ServiceAttribute : global::System.Attribute
            {
                public ServiceAttribute(ServiceLifetime lifetime, global::System.Type? serviceType = null)
                {
                    Lifetime = lifetime;
                    ServiceType = serviceType;
                }

                public ServiceLifetime Lifetime { get; }

                public global::System.Type? ServiceType { get; }
            }
        }
        """;
}
